name: PHP

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, zip, sqlite3, filter
        coverage: xdebug

    - name: Clear Composer Lock File
      run: rm composer.lock

    - name: Configure for tests
      run: mv composer.json composer.json.prod && mv composer.json.dev composer.json

    - name: Install Dependencies
      run: composer install --no-interaction

    - name: Execute Tests
      run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
